# Generated by Django 4.0.1 on 2022-01-27 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='lembrete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeLembrete', models.CharField(max_length=200)),
                ('descricaoLembrete', models.CharField(max_length=300)),
                ('fileLembrete', models.FileField(null=True, upload_to='media/')),
            ],
        ),
    ]
