# Generated by Django 4.0.1 on 2022-01-27 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lembretes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lembrete',
            old_name='descricaoLembrete',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='lembrete',
            old_name='fileLembrete',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='lembrete',
            old_name='nomeLembrete',
            new_name='nome',
        ),
    ]
