# Generated by Django 4.0.1 on 2022-01-27 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lembretes', '0002_rename_descricaolembrete_lembrete_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lembrete',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
