# Generated by Django 4.0.1 on 2022-02-02 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lembretes', '0004_perfil_lembrete_data_lembrete'),
    ]

    operations = [
        migrations.AddField(
            model_name='lembrete',
            name='ativo',
            field=models.BooleanField(default=False),
        ),
    ]
