# Generated by Django 4.0.1 on 2022-02-02 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lembretes', '0006_alter_perfil_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='lembrete',
            name='perfil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lembretes.perfil'),
        ),
    ]
