# Generated by Django 4.0.1 on 2022-02-03 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lembretes', '0008_lembrete_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lembrete',
            name='perfil',
        ),
    ]
