# Generated by Django 4.0.1 on 2022-02-06 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lembretes', '0009_remove_lembrete_perfil'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='lembrete',
            table='lembrete',
        ),
    ]
