# Generated by Django 4.0.1 on 2022-02-08 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lembretes', '0010_alter_lembrete_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lembrete',
            old_name='ativo',
            new_name='concluido',
        ),
        migrations.AddField(
            model_name='lembrete',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Criação'),
        ),
    ]
