# Generated by Django 4.0.1 on 2022-02-08 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lembretes', '0013_alter_lembrete_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lembrete',
            name='descricao',
            field=models.CharField(blank=True, max_length=300, verbose_name='Descrição'),
        ),
    ]
